var data = [
  {
    name: "EMPRESA BRASILEIRA DE SERVICOS HOSPITALARES - EBSERH",
    value: 38970,
    uf: 53,
    natureza: "2011",
  },
  {
    name: "MGS MINAS GERAIS ADMINISTRACAO E SERVICOS",
    value: 24950,
    uf: 31,
    natureza: "2011",
  },
  {
    name: "COMPANHIA MUNICIPAL DE LIMPEZA URBANA - COMLURB",
    value: 20272,
    uf: 33,
    natureza: "2038",
  },
  {
    name: "PLANSUL PLANEJAMENTO E CONSULTORIA",
    value: 16593,
    uf: 42,
    natureza: "2062",
  },
  {
    name: "MRV CONSTRUCOES",
    value: 15860,
    uf: 31,
    natureza: "2062",
  },
  {
    name: "ITAU UNIBANCO",
    value: 14874,
    uf: 35,
    natureza: "2054",
  },
  {
    name: "COMPANHIA SIDERURGICA NACIONAL",
    value: 13443,
    uf: 33,
    natureza: "2046",
  },
  {
    name: "GUIMA-CONSECO CONSTRUCAO, SERVICOS E COMERCIO",
    value: 12079,
    uf: 35,
    natureza: "2062",
  },
  {
    name: "GRENDENE",
    value: 12061,
    uf: 23,
    natureza: "2046",
  },
  {
    name: "BANCO SANTANDER (BRASIL)",
    value: 11797,
    uf: 35,
    natureza: "2046",
  },
  {
    name: "COMPANHIA DE SANEAMENTO DE MINAS GERAIS COPASA MG",
    value: 11243,
    uf: 31,
    natureza: "2038",
  },
  {
    name: "STELLANTIS AUTOMOVEIS BRASIL",
    value: 10634,
    uf: 31,
    natureza: "2062",
  },
  {
    name: "TUPY",
    value: 10254,
    uf: 42,
    natureza: "2046",
  },
  {
    name: "ALBATROZ SEGURANCA E VIGILANCIA",
    value: 9250,
    uf: 35,
    natureza: "2062",
  },
  {
    name: "MERCEDES-BENZ DO BRASIL",
    value: 9183,
    uf: 35,
    natureza: "2062",
  },
  {
    name: "BANCO BRADESCO",
    value: 9006,
    uf: 35,
    natureza: "2046",
  },
  {
    name: "LAR COOPERATIVA AGROINDUSTRIAL",
    value: 8992,
    uf: 41,
    natureza: "2143",
  },
  {
    name: "BRASANITAS HOSPITALAR - HIGIENIZACAO E CONSERVACAO DE AMBIENTES DE SAUDE",
    value: 8578,
    uf: 35,
    natureza: "2062",
  },
  {
    name: "PETROLEO BRASILEIRO PETROBRAS",
    value: 8441,
    uf: 33,
    natureza: "2038",
  },
  {
    name: "ALPARGATAS",
    value: 8424,
    uf: 25,
    natureza: "2046",
  },
  {
    name: "VALE",
    value: 8305,
    uf: 15,
    natureza: "2046",
  },
  {
    name: "GRABER SEGURANCA",
    value: 7740,
    uf: 35,
    natureza: "2062",
  },
  {
    name: "ORBENK ADMINISTRACAO E SERVICOS",
    value: 7434,
    uf: 42,
    natureza: "2062",
  },
  {
    name: "ALGAR TECNOLOGIA E CONSULTORIA",
    value: 7280,
    uf: 31,
    natureza: "2054",
  },
  {
    name: "WHIRLPOOL",
    value: 7258,
    uf: 42,
    natureza: "2046",
  },
  {
    name: "HOSPITAL DE CLINICAS DE PORTO ALEGRE",
    value: 7062,
    uf: 43,
    natureza: "2011",
  },
  {
    name: "COMPANHIA PAULISTA DE TRENS METROPOLITANOS - CPTM",
    value: 7007,
    uf: 35,
    natureza: "2011",
  },
  {
    name: "GOIAS BUSINESS CONSULTORIA E SERVICOS",
    value: 6895,
    uf: 35,
    natureza: "2062",
  },
  {
    name: "C.VALE - COOPERATIVA AGROINDUSTRIAL",
    value: 6567,
    uf: 41,
    natureza: "2143",
  },
  {
    name: "CONTAX - EM RECUPERACAO JUDICIAL EM RECUPERACAO JUDICIAL",
    value: 6548,
    uf: 35,
    natureza: "2054",
  },
  {
    name: "STEFANINI CONSULTORIA E ASSESSORIA EM INFORMATICA",
    value: 6543,
    uf: 35,
    natureza: "2054",
  },
  {
    name: "USINAS SIDERURGICAS DE MINAS GERAIS USIMINAS",
    value: 6536,
    uf: 31,
    natureza: "2046",
  },
  {
    name: "COMPANHIA DE SANEAMENTO DO PARANA SANEPAR",
    value: 6527,
    uf: 41,
    natureza: "2038",
  },
  {
    name: "CENTRO SANEAMENTO E SERVICOS AVANCADOS",
    value: 6491,
    uf: 35,
    natureza: "2062",
  },
  {
    name: "COOPERATIVA CENTRAL AURORA ALIMENTOS",
    value: 6446,
    uf: 42,
    natureza: "2143",
  },
  {
    name: "PORTO SEGURO COMPANHIA DE SEGUROS GERAIS",
    value: 6326,
    uf: 35,
    natureza: "2054",
  },
  {
    name: "STONE INSTITUICAO DE PAGAMENTO",
    value: 6270,
    uf: 33,
    natureza: "2054",
  },
  {
    name: "GOCIL SERVICOS DE VIGILANCIA E SEGURANCA LTDA - EM RECUPERACAO JUDICIAL",
    value: 6197,
    uf: 35,
    natureza: "2062",
  },
  {
    name: "ACCENTURE DO BRASIL",
    value: 6117,
    uf: 35,
    natureza: "2062",
  },
  {
    name: "OSESP SERVICOS ESPECIALIZADOS",
    value: 6084,
    uf: 35,
    natureza: "2062",
  },
  {
    name: "VOLKSWAGEN DO BRASIL INDUSTRIA DE VEICULOS AUTOMOTORES",
    value: 6061,
    uf: 35,
    natureza: "2062",
  },
  {
    name: "SERVFAZ SERVICOS DE MAO DE OBRA",
    value: 6007,
    uf: 22,
    natureza: "2062",
  },
  {
    name: "COMPANHIA DO METROPOLITANO DE SAO PAULO - METRO",
    value: 5863,
    uf: 35,
    natureza: "2011",
  },
  {
    name: "CITROSUCO AGROINDUSTRIA",
    value: 5758,
    uf: 35,
    natureza: "2054",
  },
  {
    name: "LUPO",
    value: 5647,
    uf: 35,
    natureza: "2046",
  },
  {
    name: "USINA TRAPICHE",
    value: 5555,
    uf: 26,
    natureza: "2054",
  },
  {
    name: "EQS ENGENHARIA",
    value: 5510,
    uf: 42,
    natureza: "2054",
  },
  {
    name: "VERZANI & SANDRINI",
    value: 5447,
    uf: 35,
    natureza: "2054",
  },
  {
    name: "COPACOL-COOPERATIVA AGROINDUSTRIAL CONSOLATA",
    value: 5429,
    uf: 41,
    natureza: "2143",
  },
  {
    name: "HOSPITAL NOSSA SENHORA DA CONCEICAO",
    value: 5423,
    uf: 43,
    natureza: "2011",
  },
  {
    name: "OTIMA TRANSPORTES DE SALVADOR SPE",
    value: 5329,
    uf: 29,
    natureza: "2054",
  },
  {
    name: "FRIMESA COOPERATIVA CENTRAL",
    value: 5316,
    uf: 41,
    natureza: "2143",
  },
  {
    name: "AERIS INDUSTRIA E COMERCIO DE EQUIPAMENTOS PARA GERACAO DE ENERGIA",
    value: 5275,
    uf: 23,
    natureza: "2046",
  },
  {
    name: "USINA SERRA GRANDE",
    value: 5258,
    uf: 27,
    natureza: "2054",
  },
  {
    name: "GERDAU ACOMINAS",
    value: 5222,
    uf: 31,
    natureza: "2054",
  },
  {
    name: "VERZANI & SANDRINI SEGURANCA PATRIMONIAL",
    value: 5191,
    uf: 35,
    natureza: "2062",
  },
  {
    name: "KLABIN",
    value: 5151,
    uf: 41,
    natureza: "2046",
  },
  {
    name: "USINA PETRIBU",
    value: 5145,
    uf: 26,
    natureza: "2054",
  },
  {
    name: "EMS",
    value: 5142,
    uf: 35,
    natureza: "2054",
  },
  {
    name: "BRASANITAS EMPRESA BRASILEIRA DE SANEAMENTO E COM",
    value: 5139,
    uf: 35,
    natureza: "2062",
  },
  {
    name: "PULSE CLIENT EXPERTS",
    value: 5132,
    uf: 43,
    natureza: "2062",
  },
  {
    name: "CENTRAL ACUCAREIRA SANTO ANTONIO",
    value: 5115,
    uf: 27,
    natureza: "2054",
  },
  {
    name: "LITUCERA LIMPEZA E ENGENHARIA",
    value: 5072,
    uf: 35,
    natureza: "2062",
  },
  {
    name: "ARCELORMITTAL BRASIL",
    value: 5047,
    uf: 32,
    natureza: "2054",
  },
  {
    name: "EMPRESA MARANHENSE DE SERVICOS HOSPITALARES - EMSERH",
    value: 5044,
    uf: 21,
    natureza: "2011",
  },
  {
    name: "USINA SAO JOSE",
    value: 4886,
    uf: 26,
    natureza: "2054",
  },
  {
    name: "NOVA RIO SERVICOS GERAIS",
    value: 4885,
    uf: 33,
    natureza: "2062",
  },
  {
    name: "FORTAL TERCEIRIZACAO DE MAO DE OBRA",
    value: 4766,
    uf: 23,
    natureza: "2062",
  },
  {
    name: "EMPRESA BAIANA DE AGUAS E SANEAMENTO",
    value: 4748,
    uf: 29,
    natureza: "2038",
  },
  {
    name: "NORTE TECH SERVICOS EM ENERGIA",
    value: 4704,
    uf: 13,
    natureza: "2062",
  },
  {
    name: "NIDEC GLOBAL APPLIANCE BRASIL",
    value: 4666,
    uf: 42,
    natureza: "2062",
  },
  {
    name: "COMPANHIA ALCOOLQUIMICA NACIONAL-ALCOOLQUIMICA",
    value: 4518,
    uf: 26,
    natureza: "2054",
  },
  {
    name: "GLOBO COMUNICACAO E PARTICIPACOES",
    value: 4464,
    uf: 33,
    natureza: "2054",
  },
  {
    name: "MARCOPOLO",
    value: 4381,
    uf: 43,
    natureza: "2046",
  },
  {
    name: "ADLIM-TERCEIRIZACAO EM SERVICOS LTDA - EM RECUPERACAO JUDICIAL",
    value: 4380,
    uf: 26,
    natureza: "2062",
  },
  {
    name: "UTINGA ACUCAR E ETANOL",
    value: 4221,
    uf: 27,
    natureza: "2054",
  },
  {
    name: "LOCALIZA RENT A CAR",
    value: 4124,
    uf: 31,
    natureza: "2046",
  },
  {
    name: "USINA CORURIPE ACUCAR E ALCOOL",
    value: 4066,
    uf: 27,
    natureza: "2054",
  },
  {
    name: "USINA CAETE",
    value: 3962,
    uf: 27,
    natureza: "2054",
  },
  {
    name: "PRATI, DONADUZZI & CIA",
    value: 3880,
    uf: 41,
    natureza: "2062",
  },
  {
    name: "VOLVO DO BRASIL VEICULOS",
    value: 3864,
    uf: 41,
    natureza: "2062",
  },
  {
    name: "TRAMONTINA SA CUTELARIA",
    value: 3667,
    uf: 43,
    natureza: "2054",
  },
  {
    name: "COMPANHIA ESTADUAL DE AGUAS E ESGOTOS CEDAE",
    value: 3643,
    uf: 33,
    natureza: "2038",
  },
  {
    name: "PARATI INDUSTRIA E COMERCIO DE ALIMENTOS",
    value: 3639,
    uf: 42,
    natureza: "2062",
  },
  {
    name: "HAPVIDA ASSISTENCIA MEDICA",
    value: 3635,
    uf: 23,
    natureza: "2054",
  },
  {
    name: "USINA UNIAO E INDUSTRIA",
    value: 3578,
    uf: 26,
    natureza: "2054",
  },
  {
    name: "GONCALVES & TORTOLA",
    value: 3542,
    uf: 41,
    natureza: "2054",
  },
  {
    name: "MUTUAL SERVICOS DE LIMPEZA E CONSTRUCOES ",
    value: 3516,
    uf: 22,
    natureza: "2062",
  },
  {
    name: "CESUMAR - CENTRO DE ENSINO SUPERIOR DE MARINGA",
    value: 3502,
    uf: 41,
    natureza: "2062",
  },
  {
    name: "TUPY MINAS GERAIS",
    value: 3458,
    uf: 31,
    natureza: "2062",
  },
  {
    name: "CBSI - COMPANHIA BRASILEIRA DE SERVICOS DE INFRAESTRUTURA",
    value: 3428,
    uf: 33,
    natureza: "2054",
  },
  {
    name: "PROGEN",
    value: 3423,
    uf: 31,
    natureza: "2054",
  },
  {
    name: "MALWEE MALHAS",
    value: 3415,
    uf: 42,
    natureza: "2062",
  },
  {
    name: "NUTRIZA AGROINDUSTRIAL DE ALIMENTOS",
    value: 3397,
    uf: 52,
    natureza: "2054",
  },
  {
    name: "STIHL FERRAMENTAS MOTORIZADAS",
    value: 3343,
    uf: 43,
    natureza: "2062",
  },
  {
    name: "EPAVI VIGILANCIA",
    value: 3335,
    uf: 43,
    natureza: "2062",
  },
  {
    name: "LABORATORIO TEUTO BRASILEIRO",
    value: 3335,
    uf: 52,
    natureza: "2054",
  },
  {
    name: "AGRO INDUSTRIAS DO VALE DO SAO FRANCISCO SA AGROVALE",
    value: 3329,
    uf: 29,
    natureza: "2054",
  },
  {
    name: "SOCIEDADE MICHELIN DE PARTICIPACOES INDUST E COMERCIO",
    value: 3327,
    uf: 33,
    natureza: "2062",
  },
  {
    name: "SOFTMARKETING COMUNICACAO E INFORMACAO",
    value: 3306,
    uf: 41,
    natureza: "2062",
  },
  {
    name: "USINA CENTRAL OLHO D'AGUA",
    value: 3301,
    uf: 26,
    natureza: "2054",
  },
  {
    name: "TELEMONT ENGENHARIA DE TELECOMUNICACOES",
    value: 3298,
    uf: 31,
    natureza: "2054",
  },
  {
    name: "USINA ALTO ALEGRE - ACUCAR E ALCOOL",
    value: 3264,
    uf: 41,
    natureza: "2054",
  },
  {
    name: "COOPAVEL COOPERATIVA AGROINDUSTRIAL",
    value: 3245,
    uf: 41,
    natureza: "2143",
  },
  {
    name: "CSN - TRANSPORTES URBANOS SPE",
    value: 3244,
    uf: 29,
    natureza: "2054",
  },
  {
    name: "RANDON SA IMPLEMENTOS E PARTICIPACOES",
    value: 3229,
    uf: 43,
    natureza: "2046",
  },
  {
    name: "TAURUS ARMAS",
    value: 3217,
    uf: 43,
    natureza: "2046",
  },
  {
    name: "FLORIPARK EMPREENDIMENTOS E SERVICOS LTDA EM RECUPERACAO JUDICIAL",
    value: 3199,
    uf: 42,
    natureza: "2062",
  },
  {
    name: "TEL CENTRO DE CONTATOS",
    value: 3129,
    uf: 29,
    natureza: "2062",
  },
  {
    name: "MONDELEZ BRASIL",
    value: 3088,
    uf: 41,
    natureza: "2062",
  },
  {
    name: "DOHLER",
    value: 3071,
    uf: 42,
    natureza: "2046",
  },
  {
    name: "CONSERVO SERVICOS GERAIS",
    value: 3064,
    uf: 31,
    natureza: "2062",
  },
  {
    name: "EMPRESA GONTIJO DE TRANSPORTES",
    value: 3038,
    uf: 31,
    natureza: "2054",
  },
  {
    name: "INDUSTRIAL PORTO RICO - EM RECUPERACAO JUDICIAL",
    value: 3023,
    uf: 27,
    natureza: "2054",
  },
  {
    name: "ENGELMIG ENERGIA",
    value: 3021,
    uf: 31,
    natureza: "2062",
  },
  {
    name: "USINA SAO JOSE DO PINHEIRO",
    value: 3010,
    uf: 28,
    natureza: "2062",
  },
  {
    name: "RUDDER SEGURANCA",
    value: 2991,
    uf: 43,
    natureza: "2062",
  },
  {
    name: "USINA IPOJUCA",
    value: 2979,
    uf: 26,
    natureza: "2054",
  },
  {
    name: "ELLU TERCEIRIZACAO",
    value: 2971,
    uf: 29,
    natureza: "2062",
  },
  {
    name: "USINA SANTA CLOTILDE - EM RECUPERACAO JUDICIAL",
    value: 2937,
    uf: 27,
    natureza: "2054",
  },
  {
    name: "ORCALI SERVICOS DE LIMPEZA",
    value: 2930,
    uf: 42,
    natureza: "2062",
  },
  {
    name: "STARA - INDUSTRIA DE IMPLEMENTOS AGRICOLAS",
    value: 2923,
    uf: 43,
    natureza: "2054",
  },
  {
    name: "ARAUJO ABREU ENGENHARIA",
    value: 2908,
    uf: 33,
    natureza: "2062",
  },
  {
    name: "BANCO DO ESTADO DO RIO GRANDE DO SUL",
    value: 2882,
    uf: 43,
    natureza: "2046",
  },
  {
    name: "PREMIER LOGISTICS GESTAO EMPRESARIAL",
    value: 2880,
    uf: 29,
    natureza: "2062",
  },
  {
    name: "KARSTEN",
    value: 2863,
    uf: 42,
    natureza: "2046",
  },
  {
    name: "USIMINAS MECANICA",
    value: 2859,
    uf: 31,
    natureza: "2054",
  },
  {
    name: "JAGUAFRANGOS INDUSTRIA E COMERCIO DE ALIMENTOS",
    value: 2859,
    uf: 41,
    natureza: "2062",
  },
  {
    name: "HOSPITAL SAO RAFAEL",
    value: 2852,
    uf: 29,
    natureza: "2054",
  },
  {
    name: "APERAM INOX AMERICA DO SUL",
    value: 2832,
    uf: 31,
    natureza: "2054",
  },
  {
    name: "SJC BIOENERGIA",
    value: 2817,
    uf: 52,
    natureza: "2062",
  },
  {
    name: "DELL COMPUTADORES DO BRASIL",
    value: 2788,
    uf: 43,
    natureza: "2062",
  },
  {
    name: "WEG LINHARES EQUIPAMENTOS ELETRICOS",
    value: 2782,
    uf: 32,
    natureza: "2054",
  },
  {
    name: "HIGI SERV LIMPEZA E CONSERVACAO",
    value: 2756,
    uf: 41,
    natureza: "2054",
  },
  {
    name: "AVIVAR ALIMENTOS",
    value: 2753,
    uf: 31,
    natureza: "2054",
  },
  {
    name: "SERVNAC FACILITIES SERVICE E LOGISTICA",
    value: 2743,
    uf: 23,
    natureza: "2062",
  },
  {
    name: "CONFEDERAL VIGILANCIA E TRANSPORTE DE VALORES",
    value: 2716,
    uf: 53,
    natureza: "2062",
  },
  {
    name: "HOSPITAL SAO DOMINGOS",
    value: 2702,
    uf: 21,
    natureza: "2062",
  },
  {
    name: "PONTUAL SERVICOS TERCEIRIZADOS",
    value: 2696,
    uf: 41,
    natureza: "2062",
  },
  {
    name: "SCHULZ",
    value: 2667,
    uf: 42,
    natureza: "2046",
  },
  {
    name: "GRUPO MULTI",
    value: 2658,
    uf: 31,
    natureza: "2046",
  },
  {
    name: "COMPANHIA MUNICIPAL DE LIMPEZA URBANA DE NITEROI",
    value: 2644,
    uf: 33,
    natureza: "2038",
  },
  {
    name: "AUTO VIACAO MARECHAL",
    value: 2643,
    uf: 53,
    natureza: "2062",
  },
  {
    name: "ROBERT BOSCH LIMITADA",
    value: 2637,
    uf: 41,
    natureza: "2062",
  },
  {
    name: "MOBRA SERVICOS DE VIGILANCIA LTDA - MASSA FALIDA",
    value: 2636,
    uf: 43,
    natureza: "2062",
  },
  {
    name: "ELECTROLUX DO BRASIL",
    value: 2621,
    uf: 41,
    natureza: "2054",
  },
  {
    name: "KERUI METODO CONSTRUCAO E MONTAGEM",
    value: 2619,
    uf: 33,
    natureza: "2062",
  },
  {
    name: "LIMGER EMPRESA DE LIMPEZAS GERAIS E SERVICOS",
    value: 2617,
    uf: 42,
    natureza: "2062",
  },
  {
    name: "LOJAS RENNER",
    value: 2601,
    uf: 43,
    natureza: "2046",
  },
  {
    name: "CNS NACIONAL DE SERVICOS LIMITADA",
    value: 2586,
    uf: 33,
    natureza: "2062",
  },
  {
    name: "RIVELLI ALIMENTOS",
    value: 2578,
    uf: 31,
    natureza: "2054",
  },
  {
    name: "VIACAO PIRACICABANA",
    value: 2574,
    uf: 53,
    natureza: "2054",
  },
  {
    name: "GENERAL MOTORS DO BRASIL",
    value: 2547,
    uf: 43,
    natureza: "2062",
  },
  {
    name: "BRUNING TECNOMETAL",
    value: 2536,
    uf: 43,
    natureza: "2062",
  },
  {
    name: "LAND SERVICOS E ENGENHARIA",
    value: 2521,
    uf: 33,
    natureza: "2062",
  },
  {
    name: "EMPRESA BRASILEIRA DE CORREIOS E TELEGRAFOS",
    value: 2509,
    uf: 53,
    natureza: "2011",
  },
  {
    name: "GUARDSECURE SEGURANCA EMPRESARIAL",
    value: 2486,
    uf: 29,
    natureza: "2062",
  },
  {
    name: "SAO MARTINHO",
    value: 2475,
    uf: 52,
    natureza: "2046",
  },
  {
    name: "DILLY NORDESTE INDUSTRIA DE CALCADOS",
    value: 2455,
    uf: 23,
    natureza: "2062",
  },
  {
    name: "USINAS ITAMARATI",
    value: 2454,
    uf: 51,
    natureza: "2054",
  },
  {
    name: "FRAS-LE",
    value: 2426,
    uf: 43,
    natureza: "2046",
  },
  {
    name: "SALOBO METAIS",
    value: 2413,
    uf: 15,
    natureza: "2054",
  },
  {
    name: "MULTSERV MANUTENCAO PREDIAL",
    value: 2363,
    uf: 28,
    natureza: "2062",
  },
  {
    name: "FAZENDA DE CANA DE ACUCAR TAQUARI",
    value: 2357,
    uf: 28,
    natureza: "2062",
  },
  {
    name: "R7 FACILITIES - MANUTENCAO E SERVICOS",
    value: 2357,
    uf: 53,
    natureza: "2062",
  },
  {
    name: "LOJAS RIACHUELO",
    value: 2335,
    uf: 24,
    natureza: "2054",
  },
  {
    name: "NEOBPO SERVICOS DE PROCESSOS DE NEGOCIOS E TECNOLOGIA",
    value: 2329,
    uf: 26,
    natureza: "2054",
  },
  {
    name: "CONSTRUTORA APIA",
    value: 2306,
    uf: 15,
    natureza: "2054",
  },
  {
    name: "TECNOLIMP SERVICOS",
    value: 2269,
    uf: 41,
    natureza: "2062",
  },
  {
    name: "HAPVIDA CALL CENTER E TECNOLOGIA",
    value: 2249,
    uf: 23,
    natureza: "2062",
  },
  {
    name: "CALCADOS RAMARIM",
    value: 2219,
    uf: 43,
    natureza: "2062",
  },
  {
    name: "ORSEGUPS SEGURANCA E VIGILANCIA",
    value: 2215,
    uf: 42,
    natureza: "2062",
  },
  {
    name: "BUGIO AGROPECUARIA",
    value: 2179,
    uf: 42,
    natureza: "2062",
  },
  {
    name: "NATURALLE TRATAMENTO DE RESIDUOS",
    value: 2178,
    uf: 29,
    natureza: "2062",
  },
  {
    name: "PAMPLONA ALIMENTOS",
    value: 2140,
    uf: 42,
    natureza: "2054",
  },
  {
    name: "MINERVA",
    value: 2136,
    uf: 52,
    natureza: "2046",
  },
  {
    name: "COMPANHIA MINUANO DE ALIMENTOS",
    value: 2117,
    uf: 43,
    natureza: "2054",
  },
  {
    name: "COMPANHIA DE ELETRICIDADE DO ESTADO DA BAHIA COELBA",
    value: 2105,
    uf: 29,
    natureza: "2046",
  },
  {
    name: "C & S VIGILANCIA E SEGURANCA PATRIMONIAL",
    value: 2100,
    uf: 15,
    natureza: "2062",
  },
  {
    name: "INTELBRAS INDUSTRIA DE TELECOMUNICACAO ELETRONICA BRASILEIRA",
    value: 2067,
    uf: 42,
    natureza: "2046",
  },
  {
    name: "CGB ENERGIA",
    value: 2065,
    uf: 15,
    natureza: "2062",
  },
  {
    name: "IMETAME METALMECANICA",
    value: 2065,
    uf: 32,
    natureza: "2062",
  },
  {
    name: "DOCOL INDUSTRIA E COMERCIO",
    value: 2062,
    uf: 42,
    natureza: "2062",
  },
  {
    name: "IRMAOS PASSAURA",
    value: 2051,
    uf: 41,
    natureza: "2054",
  },
  {
    name: "PBG",
    value: 2048,
    uf: 42,
    natureza: "2046",
  },
  {
    name: "JOHN DEERE BRASIL",
    value: 2034,
    uf: 43,
    natureza: "2062",
  },
  {
    name: "EXEMPLAR SERVICE E LIMPEZA",
    value: 2028,
    uf: 29,
    natureza: "2062",
  },
  {
    name: "SERVNAC SEGURANCA",
    value: 2025,
    uf: 23,
    natureza: "2062",
  },
  {
    name: "TUCUMANN ENGENHARIA E EMPREENDIMENTOS",
    value: 2022,
    uf: 41,
    natureza: "2062",
  },
  {
    name: "COOPERATIVA DE CREDITO VALE DO ITAJAI   VIACREDI",
    value: 2003,
    uf: 42,
    natureza: "2143",
  },
  {
    name: "FLEX GESTAO DE RELACIONAMENTOS EM RECUPERACAO JUDICIAL",
    value: 1977,
    uf: 42,
    natureza: "2046",
  },
  {
    name: "WEG DRIVES & CONTROLS - AUTOMACAO",
    value: 1968,
    uf: 42,
    natureza: "2062",
  },
  {
    name: "CARRIS PORTO-ALEGRENSE",
    value: 1966,
    uf: 43,
    natureza: "2062",
  },
  {
    name: "PRODAL SAUDE",
    value: 1960,
    uf: 29,
    natureza: "2054",
  },
  {
    name: "METALURGICA MOR",
    value: 1958,
    uf: 43,
    natureza: "2054",
  },
  {
    name: "MATERNIDADE E CIRURGIA N. S. DO ROCIO",
    value: 1946,
    uf: 41,
    natureza: "2054",
  },
  {
    name: "HEINZ BRASIL",
    value: 1918,
    uf: 52,
    natureza: "2054",
  },
  {
    name: "ALFORGE SEGURANCA PATRIMONIAL",
    value: 1915,
    uf: 26,
    natureza: "2062",
  },
  {
    name: "PRI APOIO ADMINISTRATIVO E OPERACIONAL",
    value: 1911,
    uf: 13,
    natureza: "2062",
  },
  {
    name: "JSL",
    value: 1894,
    uf: 15,
    natureza: "2046",
  },
  {
    name: "LINCE - SEGURANCA PATRIMONIAL",
    value: 1894,
    uf: 43,
    natureza: "2062",
  },
  {
    name: "ORSEGUPS PRESTACAO DE SERVICOS DE LIMPEZA",
    value: 1891,
    uf: 42,
    natureza: "2062",
  },
  {
    name: "KYLY INDUSTRIA TEXTIL",
    value: 1881,
    uf: 42,
    natureza: "2062",
  },
  {
    name: "COOPERATIVA DE COLONIZACAO AGROPECUARIA E INDUSTRIAL PINDORAMA",
    value: 1861,
    uf: 27,
    natureza: "2143",
  },
  {
    name: "TERRAPLENA",
    value: 1856,
    uf: 15,
    natureza: "2062",
  },
  {
    name: "HOSPITAL PORTO DIAS",
    value: 1853,
    uf: 15,
    natureza: "2062",
  },
  {
    name: "CONCENTRIX BRASIL TERCEIRIZACAO DE PROCESSOS, SERVICOS ADMINISTRATIVOS E TECNOLOGIA EMPRESARIAL",
    value: 1853,
    uf: 23,
    natureza: "2062",
  },
  {
    name: "AGIL SERVICOS CONDOMINIAIS E CORPORATIVOS ESPECIALIZADOS",
    value: 1842,
    uf: 53,
    natureza: "2062",
  },
  {
    name: "HERVAL INDUSTRIA DE MOVEIS, COLCHOES E ESPUMAS",
    value: 1841,
    uf: 43,
    natureza: "2062",
  },
  {
    name: "AGROPECUARIA SCHIO",
    value: 1838,
    uf: 43,
    natureza: "2054",
  },
  {
    name: "CHOCOLATES GAROTO",
    value: 1828,
    uf: 32,
    natureza: "2062",
  },
  {
    name: "CIRCULO",
    value: 1820,
    uf: 42,
    natureza: "2062",
  },
  {
    name: "INTEGRACAO TRANSPORTES",
    value: 1810,
    uf: 13,
    natureza: "2062",
  },
  {
    name: "TDK ELECTRONICS DO BRASIL",
    value: 1809,
    uf: 43,
    natureza: "2062",
  },
  {
    name: "COOPERATIVA AGRICOLA DO VALE DO SATUBA - COPERVALES",
    value: 1788,
    uf: 27,
    natureza: "2143",
  },
  {
    name: "DINAMO ENGENHARIA",
    value: 1783,
    uf: 15,
    natureza: "2062",
  },
  {
    name: "USINA ESTIVAS",
    value: 1782,
    uf: 24,
    natureza: "2062",
  },
  {
    name: "PAMPEANO ALIMENTOS",
    value: 1766,
    uf: 43,
    natureza: "2054",
  },
  {
    name: "COMPANHIA BRASILEIRA DE TRENS URBANOS",
    value: 1705,
    uf: 26,
    natureza: "2011",
  },
  {
    name: "ARMAZEM MATEUS",
    value: 1669,
    uf: 21,
    natureza: "2054",
  },
  {
    name: "FRISA FRIGORIFICO RIO DOCE",
    value: 1664,
    uf: 32,
    natureza: "2054",
  },
  {
    name: "SOFTPLAN PLANEJAMENTO E SISTEMAS",
    value: 1658,
    uf: 42,
    natureza: "2054",
  },
  {
    name: "LOC-SERVICE COMERCIO E SERVICOS",
    value: 1634,
    uf: 52,
    natureza: "2062",
  },
  {
    name: "CONSTRUCAP CCPS ENGENHARIA E COMERCIO",
    value: 1631,
    uf: 51,
    natureza: "2054",
  },
  {
    name: "FMM PERNAMBUCO COMPONENTES AUTOMOTIVOS",
    value: 1625,
    uf: 26,
    natureza: "2062",
  },
  {
    name: "BELEM RIO SEGURANCA",
    value: 1610,
    uf: 15,
    natureza: "2062",
  },
  {
    name: "SAO LUCAS MEDICO HOSPITALAR",
    value: 1604,
    uf: 28,
    natureza: "2054",
  },
  {
    name: "INDUSTRIAS REUNIDAS RAYMUNDO DA FONTE",
    value: 1603,
    uf: 26,
    natureza: "2054",
  },
  {
    name: "MONDELEZ BRASIL NORTE NORDESTE",
    value: 1601,
    uf: 26,
    natureza: "2062",
  },
  {
    name: "KAPA CAPITAL FACILITIES",
    value: 1595,
    uf: 15,
    natureza: "2062",
  },
  {
    name: "COMPANHIA ACUCAREIRA CENTRAL SUMAUMA - EM RECUPERACAO JUDICIAL",
    value: 1591,
    uf: 27,
    natureza: "2054",
  },
  {
    name: "ELO CONTACT CENTER SERVICOS",
    value: 1588,
    uf: 21,
    natureza: "2054",
  },
  {
    name: "MINERACAO PARAGOMINAS",
    value: 1580,
    uf: 15,
    natureza: "2054",
  },
  {
    name: "SUSTENTARE SANEAMENTO",
    value: 1559,
    uf: 53,
    natureza: "2054",
  },
  {
    name: "ORBENK TERCEIRIZACAO E SERVICOS",
    value: 1532,
    uf: 42,
    natureza: "2062",
  },
  {
    name: "ALTENBURG TEXTIL",
    value: 1503,
    uf: 42,
    natureza: "2062",
  },
  {
    name: "SUMA BRASIL - SERVICOS URBANOS E MEIO AMBIENTE",
    value: 1498,
    uf: 53,
    natureza: "2054",
  },
  {
    name: "ORBITALL ATENDIMENTO",
    value: 1496,
    uf: 25,
    natureza: "2062",
  },
  {
    name: "TAUA BRASIL PALMA",
    value: 1488,
    uf: 15,
    natureza: "2054",
  },
  {
    name: "MIP ENGENHARIA",
    value: 1483,
    uf: 15,
    natureza: "2062",
  },
  {
    name: "ELFE OPERACAO E MANUTENCAO - EM RECUPERACAO JUDICIAL EM RECUPERACAO JUDICIAL",
    value: 1481,
    uf: 28,
    natureza: "2054",
  },
  {
    name: "CHIBATAO NAVEGACAO E COMERCIO",
    value: 1459,
    uf: 13,
    natureza: "2062",
  },
  {
    name: "SLEA - SAO LUIS ENGENHARIA AMBIENTAL",
    value: 1455,
    uf: 21,
    natureza: "2054",
  },
  {
    name: "REFLORESTADORA MARBORGES",
    value: 1441,
    uf: 15,
    natureza: "2062",
  },
  {
    name: "DNA FACILITIES",
    value: 1421,
    uf: 53,
    natureza: "2062",
  },
  {
    name: "RIO CORRENTE AGRICOLA",
    value: 1420,
    uf: 50,
    natureza: "2054",
  },
  {
    name: "MINERACAO SERRA GRANDE",
    value: 1411,
    uf: 52,
    natureza: "2054",
  },
  {
    name: "COHAMA ENGENHARIA",
    value: 1407,
    uf: 21,
    natureza: "2062",
  },
  {
    name: "DOK CALCADOS DO SERGIPE LTDA - EM RECUPERACAO JUDICIAL",
    value: 1386,
    uf: 28,
    natureza: "2062",
  },
  {
    name: "SPEEDMAIS SOLUCOES",
    value: 1366,
    uf: 26,
    natureza: "2062",
  },
  {
    name: "USINA GIASA",
    value: 1361,
    uf: 25,
    natureza: "2062",
  },
  {
    name: "CONTEC SERVICOS TERCEIRIZADOS",
    value: 1360,
    uf: 26,
    natureza: "2062",
  },
  {
    name: "SEI VIGILANCIA E SEGURANCA",
    value: 1356,
    uf: 32,
    natureza: "2062",
  },
  {
    name: "GUARAVES GUARABIRA AVES",
    value: 1354,
    uf: 25,
    natureza: "2062",
  },
  {
    name: "TRANSPORTADORA JOLIVAN",
    value: 1350,
    uf: 32,
    natureza: "2062",
  },
  {
    name: "SOCIEDADE DE EDUCACAO TIRADENTES",
    value: 1346,
    uf: 28,
    natureza: "2054",
  },
  {
    name: "BORBOREMA IMPERIAL TRANSPORTES",
    value: 1342,
    uf: 26,
    natureza: "2062",
  },
  {
    name: "VISEL VIGILANCIA E SEGURANCA",
    value: 1323,
    uf: 32,
    natureza: "2062",
  },
  {
    name: "REDE PRIMAVERA - ASSISTENCIA MEDICA HOSPITALAR",
    value: 1318,
    uf: 28,
    natureza: "2062",
  },
  {
    name: "SOLSERV SERVICOS",
    value: 1314,
    uf: 26,
    natureza: "2062",
  },
  {
    name: "PRO SERVICE CONSERVACAO E CONSTRUCAO",
    value: 1303,
    uf: 13,
    natureza: "2062",
  },
  {
    name: "UNIMED VITORIA COOPERATIVA DE TRABALHO MEDICO",
    value: 1300,
    uf: 32,
    natureza: "2143",
  },
  {
    name: "BRAMETAL",
    value: 1297,
    uf: 32,
    natureza: "2054",
  },
  {
    name: "TRANSPORTER SEGURANCA E TRANSPORTE DE VALORES LTDA EM RECUPERACAO JUDICIAL",
    value: 1259,
    uf: 21,
    natureza: "2062",
  },
  {
    name: "FENIX RH SERVICOS EMPRESARIAIS",
    value: 1258,
    uf: 13,
    natureza: "2062",
  },
  {
    name: "BRASLIMP SERVICOS",
    value: 1256,
    uf: 32,
    natureza: "2062",
  },
  {
    name: "PHILCO ELETRONICOS",
    value: 1249,
    uf: 13,
    natureza: "2054",
  },
  {
    name: "MAIA & PIMENTEL SERVICOS E CONSULTORIA",
    value: 1242,
    uf: 12,
    natureza: "2062",
  },
  {
    name: "ESTEL SERVICOS INDUSTRIAIS",
    value: 1238,
    uf: 32,
    natureza: "2062",
  },
  {
    name: "VOLARE VEICULOS",
    value: 1230,
    uf: 32,
    natureza: "2062",
  },
  {
    name: "ELCOP ENGENHARIA",
    value: 1221,
    uf: 52,
    natureza: "2062",
  },
  {
    name: "FAGUNDES CONSTRUCAO E MINERACAO",
    value: 1212,
    uf: 52,
    natureza: "2054",
  },
  {
    name: "ESTALEIRO JURONG ARACRUZ",
    value: 1203,
    uf: 32,
    natureza: "2062",
  },
  {
    name: "DEXCO HYDRA CORONA SISTEMAS DE AQUECIMENTO DE AGUA",
    value: 1202,
    uf: 28,
    natureza: "2062",
  },
  {
    name: "MINERACAO TABOCA",
    value: 1185,
    uf: 13,
    natureza: "2054",
  },
  {
    name: "TORRE EMPREENDIMENTOS RURAL E CONSTRUCAO",
    value: 1162,
    uf: 28,
    natureza: "2062",
  },
  {
    name: "CENCOSUD BRASIL COMERCIAL",
    value: 1152,
    uf: 28,
    natureza: "2062",
  },
  {
    name: "SUZANO",
    value: 1149,
    uf: 50,
    natureza: "2046",
  },
  {
    name: "EMPRESA PARAIBANA DE PESQUISA, EXTENSAO RURAL E REGULARIZACAO FUNDIARIA - EMPAER",
    value: 1137,
    uf: 25,
    natureza: "2011",
  },
  {
    name: "ENERGETICA SANTA HELENA",
    value: 1121,
    uf: 50,
    natureza: "2054",
  },
  {
    name: "GLOBAL GNZ TRANSPORTES",
    value: 1094,
    uf: 13,
    natureza: "2062",
  },
  {
    name: "NATURAL PORK ALIMENTOS",
    value: 1089,
    uf: 51,
    natureza: "2054",
  },
  {
    name: "PICPAY INSTITUICAO DE PAGAMENTO",
    value: 1085,
    uf: 32,
    natureza: "2054",
  },
  {
    name: "RAIZEN CENTRO-SUL",
    value: 1084,
    uf: 50,
    natureza: "2054",
  },
  {
    name: "CONSTRUTORA CELI",
    value: 1068,
    uf: 28,
    natureza: "2062",
  },
  {
    name: "REAL TRANSPORTES URBANOS",
    value: 1046,
    uf: 27,
    natureza: "2062",
  },
  {
    name: "ENERGISA SERGIPE - DISTRIBUIDORA DE ENERGIA",
    value: 1041,
    uf: 28,
    natureza: "2046",
  },
  {
    name: "COMPANHIA DE SANEAMENTO DO TOCANTINS - SANEATINS",
    value: 1030,
    uf: 17,
    natureza: "2054",
  },
  {
    name: "FLEX IMP.EXPORT.IND.E COMER DE MAQUIN.E MOTORES",
    value: 1024,
    uf: 13,
    natureza: "2062",
  },
  {
    name: "WHIRLPOOL ELETRODOMESTICOS AM",
    value: 1020,
    uf: 13,
    natureza: "2054",
  },
  {
    name: "ALMEIDA E CALDAS",
    value: 1007,
    uf: 51,
    natureza: "2062",
  },
  {
    name: "GILCE O PINTO",
    value: 1001,
    uf: 14,
    natureza: "2135",
  },
];
